### PR TITLE
Fix for `insert_item` after alread loaded items via `set_items`.

### PR DESCRIPTION
**Pull request by rflaperuta**
Hello @BonsaiDen / @gyscos , I had a small problem calling `insert_item` when a table is already loaded with `set_items`.

It seems that during the first copy of the items a zero index approach was used to store its positions in `row_to_items`, which is fine btw, but when calling `insert_item` after that we run in a `panic` with `out of bounds index error`.

- Bumped version to 0.8.0
- Wrote a small test case

Please, I'm pretty new to contributing PRs, your feedback is much appreciated...

Thx

### CODE REVIEW

**Comment by gyscos** [comment]
Hi, and thanks for the work - the test case is a very nice touch!

In general, you don't need to bump the version in a PR, we can do that separately (especially if we need to merge multiple PRs before a version bump). In this case, we would also likely go to 0.7.1 as it's a purely internal change.

**Comment by rflaperuta** [comment]
Hey, thanks for the feedback...

Do you want me to:
1- revert the version bump
2- Add one more test for the case you mentioned
?

**Comment by gyscos** [comment]
Either, as you wish! Though the extra test case probably isn't required for now - we may add a full battery of tests in time, but nothing pressing.

**Comment by rflaperuta** [comment]
Alright, the version bump is reset, it's up to you guys now.... Also, did a little refactoring for the tests...

Thanks for the help and the crate ;-)

**Pull request merged**
